#!/bin/bash

set -e

error(){
    echo $1
    exit 1
}


# name of host
test -n "$1" || error "need host name"
export NAME=$1


# awk program to get next valid ip
ip=$(awk -F':' -f add_host.awk host_names) || error "already registered"


# create certificate
nebula-cert sign -name "$1" -ip "192.168.42.$ip/24" -out-crt host.crt -out-key host.key



# create tar
zip host.zip host.key host.crt ca.crt config.yml

rm host.crt host.key


get_content(){
    echo "HTTP/1.1 200 OK"
    echo "Content-Type: application/zip"
    echo "Server: netcat!"
    length=$(wc --bytes < host.zip)
    echo "Content-Length: $length"
    echo ""

    cat host.zip
}

echo "wait for $1 (ip = $ip)"

# send via http
get_content | nc -l 80

echo "$ip:$1" >> host_names

rm host.zip
